DROP TRIGGER IF EXISTS test;
DELIMITER //
CREATE TRIGGER test BEFORE INSERT ON shop.products
FOR EACH ROW
BEGIN
  IF(ISNULL(NEW.name) AND ISNULL(NEW.description)) THEN
  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Отмена операции';
  END IF;
END //
DELIMITER ;